module.exports = {
    name: 'joke',
    description: 'Tells a random joke.',
    execute(message) {
        const jokes = [
            "Why don’t skeletons fight each other? They don’t have the guts.",
            "What do you call cheese that isn’t yours? Nacho cheese.",
            "Why did the bicycle fall over? Because it was two tired!",
            "What do you call fake spaghetti? An impasta!",
            "Why don’t eggs tell jokes? They’d crack each other up.",
            "How does a penguin build its house? Igloos it together.",
            "What do you get when you cross a snowman and a vampire? Frostbite.",
            "Why couldn’t the leopard play hide and seek? Because he was always spotted.",
            "What do you call a fish with no eyes? Fsh.",
            "Why was the math book sad? It had too many problems.",
            "How do you organize a space party? You planet.",
            "Why did the scarecrow win an award? He was outstanding in his field.",
            "What do you call a bear with no teeth? A gummy bear.",
            "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
            "Why are ghosts bad liars? Because you can see right through them.",
            "Why do seagulls fly over the ocean? Because if they flew over the bay, they’d be bagels.",
            "What do you call an alligator in a vest? An investigator.",
            "Why don’t scientists trust atoms? Because they make up everything.",
            "Why did the tomato turn red? Because it saw the salad dressing.",
            "Why can’t you hear a pterodactyl in the bathroom? Because it has a silent pee.",
            "What do you call a pile of cats? A meowtain.",
            "What do you call a can opener that doesn’t work? A can’t opener.",
            "Why are elevator jokes so good? They work on many levels.",
            "What did one wall say to the other wall? I’ll meet you at the corner.",
            "Why did the coffee file a police report? It got mugged.",
            "Why did the cookie go to the hospital? It felt crumby.",
            "Why don’t oysters donate to charity? Because they’re shellfish.",
            "What did the janitor say when he jumped out of the closet? Supplies!",
            "What do you call a nosy pepper? Jalapeño business!",
            "What do you call a boomerang that doesn’t come back? A stick.",
            "Why was the broom late? It swept in.",
            "What’s orange and sounds like a parrot? A carrot.",
            "Why did the computer go to the doctor? It caught a virus.",
            "Why can’t your nose be 12 inches long? Because then it would be a foot.",
            "What did the buffalo say to his son when he left? Bison.",
            "Why do cows have hooves instead of feet? Because they lactose.",
            "Why did the picture go to jail? It was framed.",
            "How do you make a tissue dance? Put a little boogie in it.",
            "Why don’t ants get sick? They have tiny ant-bodies.",
            "Why can’t you trust stairs? They’re always up to something.",
            "What’s brown and sticky? A stick.",
            "What do you call a magic dog? A Labracadabrador.",
            "Why did the chicken go to the séance? To talk to the other side.",
            "Why do bees have sticky hair? Because they use honeycombs.",
            "What’s a vampire’s favorite fruit? A blood orange.",
            "Why was the big cat disqualified from the race? Because it was a cheetah.",
            "What do you call an illegally parked frog? Toad.",
            "Why are frogs so happy? They eat whatever bugs them.",
            "What do you call a dinosaur with an extensive vocabulary? A thesaurus.",
            "Why did the golfer bring an extra pencil? In case he got into a draw.",
            "What do you call two monkeys who share an Amazon account? Prime mates.",
            "Why did the skeleton climb the tree? To get to the body shop.",
            "Why did the orange stop rolling down the hill? It ran out of juice.",
            "Why did the barber win the race? He took a shortcut.",
            "What do you call a sleeping bull? A bulldozer.",
            "Why did the banana go to the doctor? It wasn’t peeling well.",
            "How do you catch a squirrel? Climb a tree and act like a nut.",
            "Why don’t crabs give to charity? They’re shellfish.",
            "Why did the cow jump over the moon? The farmer had cold hands.",
            "Why are fish bad at basketball? They don’t like getting caught in the net.",
            "What do you call a factory that makes OK products? A satisfactory.",
            "Why don’t skeletons fight? They don’t have the guts.",
            "Why was the math teacher late to work? She took the rhombus.",
            "What do you call a funny mountain? Hill-arious.",
            "What do you call a dinosaur that crashes your car? T-Rex.",
            "Why did the grape stop in the middle of the road? It ran out of juice.",
            "Why do elephants never use computers? They’re afraid of the mouse.",
            "Why was the calendar afraid? Its days were numbered.",
            "What’s the best way to throw a space party? You planet.",
            "Why do bakers get tired easily? Because they’re always rolling in dough.",
            "What’s the difference between a well-dressed man and a dog? The man wears a suit, the dog just pants.",
            "Why are pirates called pirates? Because they arrrr.",
            "What’s a skeleton’s favorite instrument? The trom-bone.",
            "Why was the stadium so cool? It was filled with fans.",
            "What do you call a bee that’s having a bad hair day? A frisbee.",
            "Why did the scarecrow get promoted? He was outstanding in his field.",
            "What did the fish say when it swam into a wall? Dam.",
            "What do you call a belt made out of watches? A waist of time.",
            "Why was the computer cold? It left its Windows open.",
            "What do you call an alligator in a vest? An investigator.",
            "Why did the music teacher need a ladder? To reach the high notes.",
            "What do you call birds that stick together? Velcrows.",
            "Why don’t graveyards ever get overcrowded? People are dying to get in.",
            "Why did the tomato blush? It saw the salad dressing.",
            "Why can’t leopards hide? They’re always spotted.",
            "What’s black and white and red all over? A newspaper.",
            "What do you call an elf who sings? A wrapper.",
            "Why did the balloon go near the needle? It was feeling deflated.",
            "Why don’t scientists trust atoms? They make up everything."
        ];

        const randomJoke = jokes[Math.floor(Math.random() * jokes.length)];
        message.channel.send(randomJoke);
    },
};
